services:
  postgres:
    image: postgres:17
    container_name: nexora-postgres

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: nexora

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: